### ISSUE TITLE
Adding kong-oidc-auth plugin to running Kong container inside K8 cluster

### ISSUE THREAD

**Issue by yasir2000** [Optum/kong-oidc-auth#4]
How to add OIDC plugin to running Kong pod in k8, am using this helm deployment `https://bitnami.com/stack/kong/helm `with root access, and my plugins in container path `/opt/bitnami/kong/openresty/luajit/share/lua/5.1/kong/plugins`

**Comment by squidward05** [comment]
@yasir2000  This document will help you. The installed plug-in is stored under the Other tab by default。https://docs.konghq.com/kubernetes-ingress-controller/1.0.x/guides/setting-up-custom-plugins/

**Comment by jeremyjpj0916** [comment]
Above example is indeed how to handle custom plugins.
