### ISSUE TITLE
example

### ISSUE THREAD

**Issue by franviera92** [Optum/kong-oidc-auth#7]
please i need example to install, the readme is poor

**Comment by saroha87** [comment]
- For docker image file : "KongDockerfile":

`
FROM kong:2.6.0-alpine

LABEL description="Alpine + Kong 2.6.0 + kong-oidc plugin"

ENV OIDC_PLUGIN_VERSION=1.1.0-1
ENV JWT_PLUGIN_VERSION=1.1.0-1

USER root
RUN apk update && apk add git unzip build-base luarocks openssl-dev
RUN luarocks install lua-resty-jwt 0.2.2-0
RUN luarocks install lua-resty-openidc 1.7.2-1
RUN luarocks install luaossl
RUN luarocks install kong-oidc-auth
USER kong
`

- Docker image build command

` docker build  -t kongoidc:1 - < KongDockerfile`

- Then docker compose to execute


`
version: '3.7'

networks:
  drone-net:
    external: true


services:
  kong:
    image: kongoidc:1
    container_name: kong
    ports:
      - "80:8000" # Listener
      - "8101:8001" # Admin API
      - "443:8443"
      - "9444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          postgres
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PG_USER:          konguser
      KONG_PG_PASSWORD:      kongkongkong      
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      **_KONG_PLUGINS:          bundled,kong-oidc-auth_**
      KONG_LOG_LEVEL:        debug
      KONG_TRUSTED_IPS:      0.0.0.0/0,::/0
      KONG_PORT_MAPS:        80:8000, 443:8443
      JWT_KEYCLOAK_PRIORITY: 900   
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
    restart: on-failure
`

**Comment by jeremyjpj0916** [comment]
@saroha87 thanks for being a good community member with example, closing this issue.
