### ISSUE TITLE
module 'kong.singletons' not found

### ISSUE THREAD

**Issue by nvchernov** [Optum/kong-oidc-auth#9]
hi, i got this while trying to run docker container:

2023/01/28 21:31:06 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:706: error loading module 'kong.plugins.kong-oidc-auth.handler':
...cal/share/lua/5.1/kong/plugins/kong-oidc-auth/access.lua:4: **module 'kong.singletons' not found**:No LuaRocks module found for kong.singletons
        no field package.preload['kong.singletons']

can you help with this? 
thx!!!

**Comment by jeremyjpj0916** [comment]
This is resolved with latest release @nvchernov , feel free to test!
